### PR TITLE
Add application flag 1 << 11

### PR DESCRIPTION
**Pull request by dolfies**
Description is more or less a guesstimate. Not sure if this is still in use, but still worth having.

### CODE REVIEW

**Comment by LewisTehMinerz** [comment]
any notes on the name of the flag or also guessed?

**Comment by dolfies** [comment]
The name is from Discord (not 100% sure where I got it though, might have been an older client).

**Comment by LewisTehMinerz** [comment]
it'd be preferable if you got the src and linked it here

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dolfies** [comment]
> it'd be preferable if you got the src and linked it here

I don't have the original source (didn't note it down, but pretty sure it was some old client). However, a quick Google search reveals a few sources:

- [Discord API Types](https://discord-api-types.dev/api/discord-api-types-v10/enum/ApplicationFlags#RPCHasConnected)
- [An older revision of a discord-api-docs PR](https://github.com/discord/discord-api-docs/pull/2624/commits/9ac057007e24f8398d7974b1e568462c51c5e881)

**Comment by Lulalaby** [comment]
This flag is valid

**Comment by LewisTehMinerz** [comment]
i'll merge but this really needs a source

**Pull request merged**
