### PR TITLE
Document flag 21

### PR DESCRIPTION
**Pull request by ShockTr**
https://github.com/Discord-Datamining/Discord-Datamining/commit/23f62a24a9ab6b2f12d19c274646802307448dc6

### CODE REVIEW

**Comment by MeguminSama** [comment]
As far as I'm aware, that's toggled client-side. There's no guarantee that it isn't used for something else internally.

**Comment by ShockTr** [comment]
> As far as I'm aware, that's toggled client-side. There's no guarantee that it isn't used for something else internally.

There is no guarantee but client reefers it like that also the naming of the function which is added that uses this flag indicates it's general use and i don't think flags have double uses so i am sure that this is the correct way of describing this flag.

**Comment by LewisTehMinerz** [comment]
I think I'd take @MeguminSama's client side for now until we have more info.

**Comment by LewisTehMinerz** [comment]
I think I'd take @MeguminSama's client side for now until we have more info.

**Comment by RedDaedalus** [comment]
> As far as I'm aware, that's toggled client-side. There's no guarantee that it isn't used for something else internally.

Changing this setting in-app sends a PATCH request to `/users/@me` with the flag, so it's not just a client-side flag.

**Comment by MeguminSama** [comment]
Updated review

**Comment by MeguminSama** [comment]
@ShockTr any chance you could make the requested changes so we can merge this? thanks

**Comment by ShockTr** [comment]
> @ShockTr any chance you could make the requested changes so we can merge this? thanks

which requested changes i can't see one 🤔

**Comment by LewisTehMinerz** [comment]
@ShockTr Make the description more absolute and then we can merge. Since this is confirmed there's no point having a `possibly`.

**Comment by MeguminSama** [comment]
The review requested this change. 


    description: 'Forcefully disables Nitro features.'

**Comment by LewisTehMinerz** [comment]
Thank you for your contribution.

**Pull request merged**
